[all:vars]
ansible_python_interpreter=/usr/bin/python3

[webservers]
web1.example.com ansible_host=10.0.1.10
web2.example.com ansible_host=10.0.1.11

[appservers]
app1.example.com ansible_host=10.0.11.10
app2.example.com ansible_host=10.0.11.11

[dbservers]
db1.example.com ansible_host=10.0.11.20

[monitoring]
monitor1.example.com ansible_host=10.0.1.30

[all:children]
webservers
appservers
dbservers
monitoring
