# Ansible Inventory File
# Replace <EC2_PUBLIC_IP> with the IP address from `terraform output public_ip`

[webservers]
<EC2_PUBLIC_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/cloud-infra-key ansible_ssh_common_args='-o StrictHostKeyChecking=no'

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3
