---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Enable and start Nginx
  ansible.builtin.systemd:
    name: nginx
    enabled: true
    state: started

- name: Configure Nginx for reverse proxy
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/sites-available/cloud-infra
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx

- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/cloud-infra
    dest: /etc/nginx/sites-enabled/cloud-infra
    state: link
  notify: Reload Nginx

- name: Remove default Nginx site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx
